name: nomat-back
services:
  spring-app:
    image: junroot0909/nomat:${TAG:-latest}
    deploy:
      replicas: 2
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_URL}/nomat
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENTID: ${OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENTSECRET: ${OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENT_SECRET}
      JWT_KEY: ${JWT_KEY}
    networks:
      - backend
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: ssl_certificate
        target: /etc/letsencrypt/live/api.dev.nomat.live/fullchain.pem
      - source: ssl_certificate_key
        target: /etc/letsencrypt/live/api.dev.nomat.live/privkey.pem
networks:
  backend:
    driver: overlay
    attachable: true
configs:
  nginx_conf:
    file: ./nginx.conf
  ssl_certificate:
    file: /etc/letsencrypt/live/api.dev.nomat.live/fullchain.pem
  ssl_certificate_key:
    file: /etc/letsencrypt/live/api.dev.nomat.live/privkey.pem
