events {
    worker_connections 1024;
}
http {
    upstream backend {
        server spring-app:8080;
    }

    server {
        listen 443 ssl;
        server_name api.dev.nomat.live;
        ssl_certificate /etc/letsencrypt/live/api.dev.nomat.live/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.dev.nomat.live/privkey.pem;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://backend;
        }
    }

    server {
        listen 80;
        server_name api.dev.nomat.live;

        location / {
            return 301 https://$host$request_uri;
        }
    }
}
