spring:
  profiles:
    default: local
---
spring:
  config:
    activate:
      on-profile: local | test
  jpa:
    show-sql: true
  flyway:
    clean-disabled: false
app:
  cors:
    origins: http://localhost:3000/
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
app:
  cors:
    origins: https://nomat.netlify.app/
