server:
  forward-headers-strategy: framework
spring:
  config:
    activate:
      on-profile: local | test
  flyway:
    clean-disabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          discord:
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/discord"
            scope:
              - identify
              - email
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username
app:
  cors:
    origins: http://localhost:3000/
jwt:
  key: cGFzc3dvcmRwYXNzdzByZHBhNTV3MHJkcGE1NXdvcmQ
  domain: localhost
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
---
server:
  forward-headers-strategy: framework
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENTID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENTSECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "https://api.dev.nomat.live/login/oauth2/code/discord"
            scope:
              - identify
              - email
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username
app:
  cors:
    origins: https://dev.nomat.live
jwt:
  key: ${JWT_KEY}
  domain: dev.nomat.live
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
