spring:
  profiles:
    default: local
---
spring:
  config:
    activate:
      on-profile: local | test
  flyway:
    clean-disabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          discord:
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/discord"
            scope:
              - identify
              - email
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username
app:
  cors:
    origins: http://localhost:3000/
jwt:
  key: 391127b4502a4730af75ad2972a6a129c71b25b18cbb240ca7b6589fc83691fc332621329d6fd4bd33d8d5d1cfe07024942db1ca1099e6f087a62d601a8c69c56b4818266b17a799dd9afd09c7a101b84843050434a66c96796fc8fb9c92b1ba9fd659e2ada8a9092df0134bce96b2e617a76c80164abd715d7959e6611bfd0ff02caaa7bb73be72941ed944c80ca6fb2f4ca117b4177ed884ee735d71bd65966f29317240a38b10e43fd770b6cbd14f2d2e9b4ff04e3696c24960d1fc63fd7cefa923538e29f4b473e11210fbd04753a181e0babfe4968a06df34a9598a9f51248ff022be05ffbe7b0428531fe085ca1895ee0c86532f6f8f9e3044b5ef3809
  domain: localhost
---
server:
  forward-headers-strategy: framework
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          discord:
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/discord"
            scope:
              - identify
              - email
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username
app:
  cors:
    origins: https://dev.nomat.live
jwt:
  domain: .nomat.live
