management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
        info: info
      exposure:
        include: health, info
  endpoint:
    health:
      show-components: always
      show-details: when-authorized
      cache:
        time-to-live: 10s
app:
  health:
    pubsub:
      timeout-ms: 2000
      channel-prefix: health:pubsub
spring:
  modulith:
    events:
      completion-mode: DELETE
      republish-outstanding-events-on-restart: false
      jdbc:
        schema-initialization:
          enabled: false
  task:
    execution:
      pool:
        core-size: 4
        max-size: 16
        queue-capacity: 1000
---
server:
  forward-headers-strategy: framework
spring:
  config:
    activate:
      on-profile: local | test
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
      data-source-properties:
        rewriteBatchedStatements: true
  flyway:
    clean-disabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        rewrite_batched_statements: true
        jdbc:
          batch_size: 1000
        id:
          optimizer:
            pooled:
              preferred: pooled-lo
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          discord:
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/discord"
            scope:
              - identify
              - email
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username
app:
  cors:
    origins: http://localhost:5173/
jwt:
  key: cGFzc3dvcmRwYXNzdzByZHBhNTV3MHJkcGE1NXdvcmQ
  domain: localhost
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
---
server:
  forward-headers-strategy: framework
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
      data-source-properties:
        rewriteBatchedStatements: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  elasticsearch:
    uris: ${ELASTICSEARCH_HOSTS}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        rewrite_batched_statements: true
        jdbc:
          batch_size: 1000
        id:
          optimizer:
            pooled:
              preferred: pooled-lo
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENTID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENTSECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "https://api.dev.nomat.live/login/oauth2/code/discord"
            scope:
              - identify
              - email
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username
app:
  cors:
    origins: https://dev.nomat.live
jwt:
  key: ${JWT_KEY}
  domain: dev.nomat.live
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
