apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-certificate-no: "33361"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
  name: alb-ingress
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: back-service
      port:
        name: http
