apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomat-back-deployment
  labels:
    app: spring
spec:
  selector:
    matchLabels:
      app: nomat-back
  template:
    metadata:
      labels:
        app: nomat-back
    spec:
      containers:
        - name: nomat-back
          image: junroot0909/nomat:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: nomat-config
                  key: spring_profiles_active
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: nomat-secret
                  key: db_url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nomat-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nomat-secret
                  key: db_password

