apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization
resources:
  - back-alb-ingress.yaml
  - back-autoscaler.yaml
  - back-deployment.yaml
  - back-service.yaml
images:
  - name: junroot0909/nomat
    newTag: latest
