services:
  spring-app:
    image: junroot0909/nomat:latest
    deploy:
      replicas: 2
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        monitor: 60s
        failure_action: rollback
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_URL}/nomat
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENTID: ${OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENTSECRET: ${OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENT_SECRET}
      JWT_KEY: ${JWT_KEY}
      LOGSTASH_URL: ${LOGSTASH_URL}
    networks:
      - backend
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    configs:
      - source: nginx_conf-2
        target: /etc/nginx/nginx.conf
      - source: ssl_certificate-1
        target: /etc/letsencrypt/live/api.dev.nomat.live/fullchain.pem
      - source: ssl_certificate_key-1
        target: /etc/letsencrypt/live/api.dev.nomat.live/privkey.pem
networks:
  backend:
    name: backend
    driver: overlay
    attachable: true
configs:
  # config 파일은 수정이 필요하면, config key 값을 변경해야 적용 됨
  nginx_conf-2:
    file: ./nginx.conf
  ssl_certificate-1:
    file: /etc/letsencrypt/live/api.dev.nomat.live/fullchain.pem
  ssl_certificate_key-1:
    file: /etc/letsencrypt/live/api.dev.nomat.live/privkey.pem
