name: Backend's pull request
on:
  pull_request:
    paths:
      - "back/**"
jobs:
  gradle-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Run tests
        run: |
          cd back
          ./gradlew clean test
  detekt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: detekt
        run: |
          cd back
          chmod +x gradlew
          ./gradlew detekt
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat ./back/build/reports/detekt.xml | reviewdog -f=checkwtyl -name="detekt" -reporter="github-pr-review" -level="warning"
