on:
  pull_request:
    paths:
      - "back/**"
jobs:
  gradle-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java#3
        with:
          java-version: "17"
          distribution: "temurin"
      - run: |
          cd back
          ./gradlew clean test
